---
- name: install epel release
  yum: name={{item}} state=installed
  with_items:
    - epel-release
  tags: common-packages

- name: install common packages
  yum: name={{item}} enablerepo=epel state=installed
  with_items:
    - git
    - yum-utils
    - telnet
    - wget
  tags: common-packages
